name: GitHub Actions Bot

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  process_pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: |
          echo "PAT=${{ secrets.PAT }}" > .env
          echo "REPO_OWNER=${{ github.repository_owner }}" >> .env
          echo "REPO_NAME=${{ github.event.repository.name }}" >> .env
          echo "REVIEWERS=${{ secrets.REVIEWERS || github.repository_owner }}" >> .env
          echo "SLACK=${{ secrets.SLACK }}" >> .env

      - name: Run PR processing script
        run: |
          node -e "
          const fs = require('fs');
          const { handlePullRequest } = require('./index.js');
          
          // Read the event payload
          const eventPayload = JSON.parse(fs.readFileSync('${{ github.event_path }}', 'utf8'));
          
          // Process the pull request
          handlePullRequest(eventPayload)
            .then(result => {
              console.log('Processing result:', result);
              if (!result.success) process.exit(1);
            })
            .catch(error => {
              console.error('Error:', error);
              process.exit(1);
            });
          "
        env:
          PAT: ${{ secrets.PAT }}
          SLACK: ${{ secrets.SLACK }}